database:
  host: localhost
  port: 5432
  username: postgres
  password: Stinkistinki33_
  name: postgres
keycloak:
  url: http://127.0.0.1:8080
  realm: Nalgon-Warriors-Dev
  clients:
    login:
      clientId: nalgon-login
      secret: 7P9VKMFCEV8IsFQqUBxIYyp6F1OyGaKN
    admin:
      clientId: nalgon-admin
      secret: Qz1cp3U9llxLGthcs89RWEOj28BqDFrw
